baseURL: "https://asasamori.github.io/"
languageCode: "en-us"
title: "Andrew Sasamori"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#     main:
#     - identifier: Gallery
#       name: Gallery
#       title: Gallery  # Changed from "Blog posts" to "Gallery"
#       url: /gallery
#       weight: 1

#Dropdown menu
# - identifier: dropdown
#   title: Example dropdown menu
#   name: Dropdown
#   weight: 3
# - identifier: dropdown1
#   title: example dropdown 1
#   name: example 1
#   url: /#
#   parent: dropdown
#   weight: 1
# - identifier: dropdown2
#   title: example dropdown 2
#   name: example 2
#   url: /#
#   parent: dropdown
#   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/sunglasses.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Andrew Sasamori" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: false
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      # TODO: Add achievements
      disableAchievements: true
      disableContact: false
      # disableGallery: false # This probably doens't do anything

  # Hero
  hero:
    enable: true
    title: "Andrew Sasamori"
    subtitle: "Software Developer and Machine Learning Researcher"
    content: >- 
      Happy that you are here!
      
      
      # Currently looking for Winter/Spring 2025 internships and/or New Grad roles for 2025


      # ... but also applying for a PhD at the same time.

    image: "/images/fun.jpeg"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/Resume.pdf"
      image:
      download: true
      newPage: false
    socialLinks:
      customIcons:
        - icon: /images/linkedin.svg
          url: https://www.linkedin.com/in/andrew-sasamori/
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/asasamori

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/cold_yosemite.jpg"
    content: >-

      Hi there! I am Andrew Sasamori, and I'm originally from <a href="https://en.wikipedia.org/wiki/Mountain_View,_California" 
      target="_blank" rel="noopener noreferrer">Mountain View</a> (Bay Area), California. For the 2024-2025 school year, 
      I am a 4th year <a href="https://www.bu.edu/academics/eng/programs/computer-engineering/bs/" target="_blank" 
      rel="noopener noreferrer">Computer Engineering</a> student concentrating in <a href="https://www.bu.edu/eng/academics/explore-degree-programs/concentration-in-machine-learning/" 
      target="_blank" rel="noopener noreferrer">Machine Learning</a> at <a href="https://www.bu.edu/" 
      target="_blank" rel="noopener noreferrer">Boston University</a>, 
      where I am a Undergraduate Research Assistant at the <a href="https://tyw-lab.github.io/" 
      target="_blank" rel="noopener noreferrer">Tianyu Wang Research Lab</a>.


      In May 2022, I transferred from <a href="https://manoa.hawaii.edu/" 
      target="_blank" rel="noopener noreferrer">University of Hawaii at Manoa</a> (as a <a href="https://cms.ctahr.hawaii.edu/majors/be" 
      target="_blank" rel="noopener noreferrer">Biological Engineering</a> student) to my current institution of Boston University. 
      I have since ommitted this information from my resume because a surprising amount of employers had thought I had completed the major
      within 1 school year.
    skills:
      enable: true
      title: "Recent technologies:"
      items:
        - "Python"
        - "JavaScript/HTML"
        - "C++"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Undergraduate Research Assistant"
        company: "Tianyu Wang Lab"
        companyUrl: "https://tyw-lab.github.io/"
        date: "Jan 2024 - Present"
        info:
          enable: false
          content: Professor Ndao switched from Boston University to UCSD
        content: |
          Periodically explaining applicable ML for optics

          - PI: <a href="https://www.bu.edu/eng/profile/tianyu-wang-phd/" target="_blank" rel="noopener noreferrer">Tianyu Wang</a>

      - job: "Software Test Engineering Co-op"
        company: "Draper"
        companyUrl: "https://www.draper.com/"
        date: "Sep 2024 - Nov 2024"
        info:
          enable: false
        content: "Validation Testing"

      - job: "Device Engineering Intern"
        company: "Alarm"
        companyUrl: "https://alarm.com"
        date: "June 2024 - Aug 2024"
        info:
          enable: false
        content: "Visualization for I/O and ports"
      - job: "Software Engineering Intern"
        company: "Lockheed Martin Space"
        companyUrl: "https://www.lockheedmartin.com/"
        date: "May 2023 - Aug 2023"
        featuredLink:
          name: NGI Program
          enable: true
          url: "https://www.lockheedmartin.com/en-us/products/next-generation-interceptor.html"
        info:
          enable: false
        content: |
          NGI components in SysML

      - job: "Undergraduate Research Assistant"
        company: "Ndao Lab"
        companyUrl: "http://ndao.ucsd.edu/"
        date: "Sep 2022 - May 2023"
        info:
          enable: true
          content: Professor Ndao switched from Boston University to UCSD
        content: |
          ML/AI Physics Simulation using Lumerical

          - PI: Abdoulaye Ndao
          - PhD Student: Saeed Hemayat

      - job: "Undergraduate Research Assistant"
        company: "Morphable Biorobotics"
        companyUrl: "https://sites.bu.edu/ranzani-lab/"
        date: "May 2022 - Sep 2023"
        info:
          enable: false
        content: |
          GUI Integration, FEA Simulations

      - job: "Undergraduate Research Assistant"
        company: "UH Manoa"
        companyUrl: "https://me.hawaii.edu/people/berkelman/"
        date: "Jan 2022 - May 2022"
        info:
          enable: false
        content: "Magnetic Levitation with surgical robotics"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Boston University"
          url: "https://bu.edu"
        date: "2022 - 2025"
        GPA: "3.6 out of 4.0"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School"
        school:
          name: "Mountain View High School"
          url: "https://mvhs.mvla.net/"
        date: "2017 - 2021"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    # TODO: Add achievements
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a   theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: BUtLAR, A Voice-Powered Digital Human Assistant
        content:
         BUtLAR (Boston University LLM Auditory Responder) is a voice-powered digital human assistant that enhances 
         personalized human-machine interaction through seamless speaker identification, noise immunity, and real-time, context-aware responses.
         Designed for diverse applications, BUtLAR addresses the limitations of traditional chatbots by delivering 
         dynamic, accessible, and conversational experiences across various environments.
        image: /images/yobe.png
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "Yobe SDK"
          - "Google Cloud"
          - "LLMs/Transformers"
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/ASasamori/BUtLAR_Voice-Powered-Digital_Human_Assistant
          - icon: fab fa-google-drive
            url: https://docs.google.com/document/d/1nvjUT8SBX4aWWRxmYNE2X7lf09815ER7deOy5cTyFGs/edit?tab=t.0
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Asynch Batch Processing Solution for Cloud-LLMs
        content: The vision of this project is to create an automated, scalable, and efficient asynchronous batch processing solution for cloud-based Large Language Models (LLMs) at Two Sigma, enabling effortless data backfilling for large-scale financial datasets. By removing the complexity of rate limits imposed by cloud LLM providers and minimizing the need for manual oversight, this solution will allow for processing large amounts of data in an optimized and timely manner, ultimately improving operational capabilities. Mentors are from Two Sigma. Stefan + Mayur
        image: /images/LLM_batch.png
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "Docker"
          - "LLMs"
          - "Google Cloud"
          - "Redis"
          - "Flask"
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/ASasamori/PokerProPlus
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
  
      - title: Poker Pro Plus
        content: Deep-Reinforcement Learning based poker AI created during my deep learning course, inspired by my short-lived losses of losing at 1/2 NLH.
        image: /images/Poker_Pro_Plus.png
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "PyTorch"
          - "Keras"
          - "Python"
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/ASasamori/PokerProPlus
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Autonomous Rover Navigation Sub-Team
        content: Path planning algorithms using a NVIDIA Jetson Nano
        image: /images/BUMRC.jpeg
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
          - "C++"
          - "ROS"
          - "Cuda"
        links:
          - icon: fab fa-github
            url: https://github.com/BUMRC

      - title: Dynamic Playlist Curation
        content: Flutter based application to allocate a 10-song playlist based on variety of metrics; weather, time of day, mood.
        image: /images/dynamic_playlist_curator.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Flutter"
          - "Dart"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/onkr0d/HackHarvard22-Repo
  #TODO:
  # Add sections that are dynamic that show top whatever for like Spotify, booklists, etc. Hopefully would call to the Spotify API and so forth

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Email me!
    btnName: Mail
    btnLink: mailto:sasamori@bu.edu
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      # Only github, linkedin, x, instagram, facebook available
      github: https://github.com/asasamori
      linkedin: https://www.linkedin.com/in/andrew-sasamori/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    # copyright: "All rights reserved"
    # TODO: Change the version so not part of copyright; find year; find way to get rid of made with love...
    copyright: "Version 1.2"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
